name: Daily Title Reading

on: 
  schedule: 
  # run this daily at 11pm UTC to get as many of the files as possible
    - cron: '50 23 * * *'
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest

    env:
      # DB_PATH: '/workspaces/stock_evaluator/article_titles/titles.db'
      DB_PATH: '/home/runner/work/stock_evaluator/stock_evaluator/article_titles/titles.db'

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      
      - name: Show current working directory
        run: pwd

      - name: List files in current directory
        run: ls -l
      
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python version: 'latest'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # testing: Download the database
      # - name: Download database artifact
      #   uses: actions/download-artifact@v4
      #   with: 
      #     name: 


      - name: Run daily read
        run: |
          python title_reader.py
